version: "2"
plugins:
  rubocop:
    enabled: true
    exclude_patterns:
    - "config/"
    - "db/"
    - "dist/"
    - "features/"
    - "**/node_modules/"
    - "script/"
    - "**/spec/"
    - "**/test/"
    - "**/tests/"
    - "Tests/"
    - "**/vendor/"
    - "**/*.d.ts"
    - "*.test.ts"
    - "public/vs/"
    - "src/app/styles/built/"
  eslint:
    enabled: true